### ISSUE TITLE
Solutions

### ISSUE THREAD

**Issue by adius** [callumacrae/regex-tuesday#9]
Nice website! However, you should post the best solutions somewhere! Or did i just not find them?

**Comment by callumacrae** [comment]
Thanks! If you click the Reddit link, people have been posting their solutions there. I didn't want a section of the website specifically for "solutions", as there isn't really such a thing - there are many different expressions to solve each challenge, some of which are better than others, the best of which are impossible to discern between.

**Comment by adius** [comment]
I expected you to say something like this, but i hoped you wouldn't. :-P
However, it would be really really cool if you could sum up all the learnings from all the different approaches and write maybe a few words underneath the challenge with good solutions, maybe also solutions which didn't not fully pass the challenge but could be useful in real world problems. I think this would also add huge value to the website and would make it a great ressource for later studies!

**Comment by callumacrae** [comment]
Alright, thanks for the suggestion! Would a monthly write up of the last four challenges on my blog (lynx.io) do? :-)

**Comment by adius** [comment]
Not optimal, but definitely a good start! Thanks! :smiley:

Can't wait for your next challenges! Keep up the good work! =)
